/* 
   Generated by bdf2lvgl (https://github.com/summivox/bdf2lvgl)
   bdf2lvgl HelveticaBold-12n.bdf -n lv_font_helvetica_bold_12
*/

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif
#ifndef LV_FONT_HELVETICA_BOLD_12
#define LV_FONT_HELVETICA_BOLD_12 1
#endif

#if LV_FONT_HELVETICA_BOLD_12

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0020 ' ' */
    0x00,

    /* U+0021 '!' */
    0xff,
    0xa3,

    /* U+0022 '"' */
    0xb6,
    0x80,

    /* U+0023 '#' */
    0x51,
    0x4f,
    0xd4,
    0xfa,
    0x8a,
    0x00,

    /* U+0024 '$' */
    0x23,
    0xab,
    0xc7,
    0x1e,
    0xae,
    0x20,

    /* U+0025 '%' */
    0x63,
    0x69,
    0xa0,
    0x81,
    0x05,
    0x95,
    0xc6,

    /* U+0026 '&' */
    0x71,
    0xb3,
    0x63,
    0x8d,
    0xf9,
    0xb7,
    0x3b,

    /* U+0027 "'" */
    0xe0,

    /* U+0028 '(' */
    0x2d,
    0x6d,
    0xb2,
    0x64,

    /* U+0029 ')' */
    0x99,
    0x36,
    0xda,
    0xd0,

    /* U+002A '*' */
    0xaa,
    0x80,

    /* U+002B '+' */
    0x30,
    0xcf,
    0xcc,
    0x30,

    /* U+002C ',' */
    0x56,

    /* U+002D '-' */
    0xf0,

    /* U+002E '.' */
    0xc0,

    /* U+002F '/' */
    0x11,
    0x22,
    0x44,
    0x88,

    /* U+0030 '0' */
    0x76,
    0xf7,
    0xbd,
    0xef,
    0x6e,

    /* U+0031 '1' */
    0x3f,
    0x33,
    0x33,
    0x33,

    /* U+0032 '2' */
    0x76,
    0xc6,
    0x33,
    0x33,
    0x1f,

    /* U+0033 '3' */
    0x76,
    0xc6,
    0x61,
    0x8f,
    0x6e,

    /* U+0034 '4' */
    0x18,
    0xe5,
    0x96,
    0x9b,
    0xf1,
    0x86,

    /* U+0035 '5' */
    0xfe,
    0x31,
    0xe1,
    0xcf,
    0x6e,

    /* U+0036 '6' */
    0x76,
    0xf1,
    0xed,
    0xef,
    0x6e,

    /* U+0037 '7' */
    0xf8,
    0xc6,
    0x63,
    0x19,
    0x8c,

    /* U+0038 '8' */
    0x76,
    0xf6,
    0xed,
    0xef,
    0x6e,

    /* U+0039 '9' */
    0x76,
    0xf7,
    0xb7,
    0x8f,
    0x6e,

    /* U+003A ':' */
    0xcc,

    /* U+003B ';' */
    0x50,
    0x56,

    /* U+003C '<' */
    0x36,
    0xc6,
    0x30,

    /* U+003D '=' */
    0xf8,
    0x3e,

    /* U+003E '>' */
    0xc6,
    0x36,
    0xc0,

    /* U+003F '?' */
    0x76,
    0xc6,
    0x66,
    0x30,
    0x0c,

    /* U+0040 '@' */
    0x1f,
    0x18,
    0x24,
    0xd6,
    0x49,
    0xa2,
    0x69,
    0x29,
    0xb1,
    0x00,
    0x3e,
    0x00,

    /* U+0041 'A' */
    0x38,
    0x71,
    0xb3,
    0x66,
    0xdf,
    0xf1,
    0xe3,

    /* U+0042 'B' */
    0xfb,
    0x3c,
    0xfe,
    0xcf,
    0x3c,
    0xfe,

    /* U+0043 'C' */
    0x3c,
    0xcf,
    0x0e,
    0x0c,
    0x18,
    0x59,
    0x9e,

    /* U+0044 'D' */
    0xf3,
    0x6c,
    0xf3,
    0xcf,
    0x3d,
    0xbc,

    /* U+0045 'E' */
    0xfe,
    0x31,
    0xfc,
    0x63,
    0x1f,

    /* U+0046 'F' */
    0xfe,
    0x31,
    0xec,
    0x63,
    0x18,

    /* U+0047 'G' */
    0x3c,
    0xcf,
    0x0e,
    0x0c,
    0xf8,
    0xd9,
    0x9d,

    /* U+0048 'H' */
    0xcf,
    0x3c,
    0xff,
    0xcf,
    0x3c,
    0xf3,

    /* U+0049 'I' */
    0xff,
    0xff,

    /* U+004A 'J' */
    0x18,
    0xc6,
    0x31,
    0x8f,
    0x6e,

    /* U+004B 'K' */
    0xcd,
    0xb3,
    0xc7,
    0x0f,
    0x1b,
    0x33,
    0x63,

    /* U+004C 'L' */
    0xc6,
    0x31,
    0x8c,
    0x63,
    0x1f,

    /* U+004D 'M' */
    0xc1,
    0xf1,
    0xf8,
    0xfe,
    0xfd,
    0x5e,
    0xef,
    0x27,
    0x93,

    /* U+004E 'N' */
    0xc7,
    0xcf,
    0x9e,
    0xbd,
    0x79,
    0xf3,
    0xe3,

    /* U+004F 'O' */
    0x38,
    0xdb,
    0x1e,
    0x3c,
    0x78,
    0xdb,
    0x1c,

    /* U+0050 'P' */
    0xfb,
    0x3c,
    0xf3,
    0xfb,
    0x0c,
    0x30,

    /* U+0051 'Q' */
    0x38,
    0xdb,
    0x1e,
    0x3c,
    0x7a,
    0xdb,
    0x1e,
    0x02,

    /* U+0052 'R' */
    0xfb,
    0x3c,
    0xf3,
    0xfb,
    0x3c,
    0xf3,

    /* U+0053 'S' */
    0x7b,
    0x3e,
    0x1e,
    0x1e,
    0x3c,
    0xde,

    /* U+0054 'T' */
    0xfc,
    0xc3,
    0x0c,
    0x30,
    0xc3,
    0x0c,

    /* U+0055 'U' */
    0xcf,
    0x3c,
    0xf3,
    0xcf,
    0x3c,
    0xde,

    /* U+0056 'V' */
    0xc7,
    0x8d,
    0xb3,
    0x66,
    0xc7,
    0x0e,
    0x08,

    /* U+0057 'W' */
    0xcc,
    0xf3,
    0x3c,
    0xcd,
    0xb6,
    0x6d,
    0x9f,
    0xe3,
    0x30,
    0x84,

    /* U+0058 'X' */
    0xc7,
    0x8d,
    0xb1,
    0xc3,
    0x8d,
    0xb1,
    0xe3,

    /* U+0059 'Y' */
    0xc3,
    0xc3,
    0x66,
    0x66,
    0x3c,
    0x18,
    0x18,
    0x18,

    /* U+005A 'Z' */
    0xfc,
    0x31,
    0x8c,
    0x71,
    0x8c,
    0x3f,

    /* U+005B '[' */
    0xfb,
    0x6d,
    0xb6,
    0xdc,

    /* U+005C '\\' */
    0x88,
    0x44,
    0x22,
    0x11,

    /* U+005D ']' */
    0xed,
    0xb6,
    0xdb,
    0x7c,

    /* U+005E '^' */
    0x23,
    0xb7,
    0x10,

    /* U+005F '_' */
    0xfc,

    /* U+0060 '`' */
    0x90,

    /* U+0061 'a' */
    0x72,
    0x67,
    0xb6,
    0xd9,
    0xb0,

    /* U+0062 'b' */
    0xc6,
    0x3d,
    0xbc,
    0xe7,
    0x7e,

    /* U+0063 'c' */
    0x7d,
    0xcc,
    0xd7,

    /* U+0064 'd' */
    0x18,
    0xdf,
    0xb9,
    0xcf,
    0x6f,

    /* U+0065 'e' */
    0x76,
    0xff,
    0x8d,
    0xb8,

    /* U+0066 'f' */
    0x7c,
    0xec,
    0xcc,
    0xcc,

    /* U+0067 'g' */
    0x6e,
    0xe7,
    0x3d,
    0xbc,
    0x6e,

    /* U+0068 'h' */
    0xc6,
    0x3d,
    0xbd,
    0xef,
    0x7b,

    /* U+0069 'i' */
    0xcf,
    0xff,

    /* U+006A 'j' */
    0xcf,
    0xff,
    0xe0,

    /* U+006B 'k' */
    0xc3,
    0x0d,
    0xbc,
    0xe3,
    0xcd,
    0xb3,

    /* U+006C 'l' */
    0xff,
    0xff,

    /* U+006D 'm' */
    0xb6,
    0xdb,
    0xdb,
    0xdb,
    0xdb,
    0xdb,

    /* U+006E 'n' */
    0xb6,
    0xf7,
    0xbd,
    0xec,

    /* U+006F 'o' */
    0x76,
    0xf7,
    0xbd,
    0xb8,

    /* U+0070 'p' */
    0xb6,
    0xf3,
    0x9d,
    0xfb,
    0x18,

    /* U+0071 'q' */
    0x6e,
    0xe7,
    0x3d,
    0xbc,
    0x63,

    /* U+0072 'r' */
    0xbe,
    0xcc,
    0xcc,

    /* U+0073 's' */
    0x76,
    0xdc,
    0x3d,
    0xb8,

    /* U+0074 't' */
    0xdb,
    0xed,
    0xb3,

    /* U+0075 'u' */
    0xde,
    0xf7,
    0xbd,
    0xb4,

    /* U+0076 'v' */
    0xde,
    0xf6,
    0xa7,
    0x10,

    /* U+0077 'w' */
    0xd7,
    0xaf,
    0x5b,
    0x66,
    0xcd,
    0x80,

    /* U+0078 'x' */
    0xcd,
    0xe3,
    0x1e,
    0xcf,
    0x30,

    /* U+0079 'y' */
    0xde,
    0xf7,
    0xb7,
    0x98,
    0xcc,

    /* U+007A 'z' */
    0xf8,
    0xcc,
    0xcc,
    0x7c,

    /* U+007B '{' */
    0x36,
    0x66,
    0xc6,
    0x66,
    0x63,

    /* U+007C '|' */
    0xff,
    0xc0,

    /* U+007D '}' */
    0xc6,
    0x66,
    0x36,
    0x66,
    0x6c,

    /* U+007E '~' */
    0x6f,
    0x60,

};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}, /* U+0000 '\x00' */
    {.bitmap_index = 0, .adv_w = 48, .box_w = 1, .box_h = 1, .ofs_x = 0, .ofs_y = 0}, /* U+0020 ' ' */
    {.bitmap_index = 1, .adv_w = 64, .box_w = 2, .box_h = 8, .ofs_x = 1, .ofs_y = 0}, /* U+0021 '!' */
    {.bitmap_index = 3, .adv_w = 80, .box_w = 3, .box_h = 3, .ofs_x = 1, .ofs_y = 5}, /* U+0022 '"' */
    {.bitmap_index = 5, .adv_w = 96, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+0023 '#' */
    {.bitmap_index = 11, .adv_w = 96, .box_w = 5, .box_h = 9, .ofs_x = 0, .ofs_y = -1}, /* U+0024 '$' */
    {.bitmap_index = 17, .adv_w = 128, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0025 '%' */
    {.bitmap_index = 24, .adv_w = 128, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0026 '&' */
    {.bitmap_index = 31, .adv_w = 48, .box_w = 1, .box_h = 3, .ofs_x = 1, .ofs_y = 5}, /* U+0027 "'" */
    {.bitmap_index = 32, .adv_w = 64, .box_w = 3, .box_h = 10, .ofs_x = 0, .ofs_y = -2}, /* U+0028 '(' */
    {.bitmap_index = 36, .adv_w = 64, .box_w = 3, .box_h = 10, .ofs_x = 0, .ofs_y = -2}, /* U+0029 ')' */
    {.bitmap_index = 40, .adv_w = 64, .box_w = 3, .box_h = 3, .ofs_x = 0, .ofs_y = 5}, /* U+002A '*' */
    {.bitmap_index = 42, .adv_w = 96, .box_w = 6, .box_h = 5, .ofs_x = 0, .ofs_y = 1}, /* U+002B '+' */
    {.bitmap_index = 46, .adv_w = 48, .box_w = 2, .box_h = 4, .ofs_x = 0, .ofs_y = -2}, /* U+002C ',' */
    {.bitmap_index = 47, .adv_w = 80, .box_w = 4, .box_h = 1, .ofs_x = 0, .ofs_y = 3}, /* U+002D '-' */
    {.bitmap_index = 48, .adv_w = 48, .box_w = 1, .box_h = 2, .ofs_x = 1, .ofs_y = 0}, /* U+002E '.' */
    {.bitmap_index = 49, .adv_w = 64, .box_w = 4, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+002F '/' */
    {.bitmap_index = 53, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0030 '0' */
    {.bitmap_index = 58, .adv_w = 96, .box_w = 4, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0031 '1' */
    {.bitmap_index = 62, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0032 '2' */
    {.bitmap_index = 67, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0033 '3' */
    {.bitmap_index = 72, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0034 '4' */
    {.bitmap_index = 78, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0035 '5' */
    {.bitmap_index = 83, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0036 '6' */
    {.bitmap_index = 88, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0037 '7' */
    {.bitmap_index = 93, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0038 '8' */
    {.bitmap_index = 98, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0039 '9' */
    {.bitmap_index = 103, .adv_w = 48, .box_w = 1, .box_h = 6, .ofs_x = 1, .ofs_y = 0}, /* U+003A ':' */
    {.bitmap_index = 104, .adv_w = 48, .box_w = 2, .box_h = 8, .ofs_x = 0, .ofs_y = -2}, /* U+003B ';' */
    {.bitmap_index = 106, .adv_w = 80, .box_w = 4, .box_h = 5, .ofs_x = 0, .ofs_y = 1}, /* U+003C '<' */
    {.bitmap_index = 109, .adv_w = 96, .box_w = 5, .box_h = 3, .ofs_x = 0, .ofs_y = 2}, /* U+003D '=' */
    {.bitmap_index = 111, .adv_w = 80, .box_w = 4, .box_h = 5, .ofs_x = 0, .ofs_y = 1}, /* U+003E '>' */
    {.bitmap_index = 114, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+003F '?' */
    {.bitmap_index = 119, .adv_w = 176, .box_w = 10, .box_h = 9, .ofs_x = 0, .ofs_y = -2}, /* U+0040 '@' */
    {.bitmap_index = 131, .adv_w = 128, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0041 'A' */
    {.bitmap_index = 138, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0042 'B' */
    {.bitmap_index = 144, .adv_w = 128, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0043 'C' */
    {.bitmap_index = 151, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0044 'D' */
    {.bitmap_index = 157, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0045 'E' */
    {.bitmap_index = 162, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0046 'F' */
    {.bitmap_index = 167, .adv_w = 128, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0047 'G' */
    {.bitmap_index = 174, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0048 'H' */
    {.bitmap_index = 180, .adv_w = 48, .box_w = 2, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0049 'I' */
    {.bitmap_index = 182, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+004A 'J' */
    {.bitmap_index = 187, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+004B 'K' */
    {.bitmap_index = 194, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+004C 'L' */
    {.bitmap_index = 199, .adv_w = 160, .box_w = 9, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+004D 'M' */
    {.bitmap_index = 208, .adv_w = 128, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+004E 'N' */
    {.bitmap_index = 215, .adv_w = 128, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+004F 'O' */
    {.bitmap_index = 222, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0050 'P' */
    {.bitmap_index = 228, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -1}, /* U+0051 'Q' */
    {.bitmap_index = 236, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0052 'R' */
    {.bitmap_index = 242, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0053 'S' */
    {.bitmap_index = 248, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0054 'T' */
    {.bitmap_index = 254, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0055 'U' */
    {.bitmap_index = 260, .adv_w = 128, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0056 'V' */
    {.bitmap_index = 267, .adv_w = 176, .box_w = 10, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0057 'W' */
    {.bitmap_index = 277, .adv_w = 128, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0058 'X' */
    {.bitmap_index = 284, .adv_w = 144, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0059 'Y' */
    {.bitmap_index = 292, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+005A 'Z' */
    {.bitmap_index = 298, .adv_w = 64, .box_w = 3, .box_h = 10, .ofs_x = 0, .ofs_y = -2}, /* U+005B '[' */
    {.bitmap_index = 302, .adv_w = 64, .box_w = 4, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+005C '\\' */
    {.bitmap_index = 306, .adv_w = 64, .box_w = 3, .box_h = 10, .ofs_x = 0, .ofs_y = -2}, /* U+005D ']' */
    {.bitmap_index = 310, .adv_w = 80, .box_w = 5, .box_h = 4, .ofs_x = 0, .ofs_y = 4}, /* U+005E '^' */
    {.bitmap_index = 313, .adv_w = 96, .box_w = 6, .box_h = 1, .ofs_x = 0, .ofs_y = -2}, /* U+005F '_' */
    {.bitmap_index = 314, .adv_w = 48, .box_w = 2, .box_h = 2, .ofs_x = 0, .ofs_y = 6}, /* U+0060 '`' */
    {.bitmap_index = 315, .adv_w = 96, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+0061 'a' */
    {.bitmap_index = 320, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0062 'b' */
    {.bitmap_index = 325, .adv_w = 80, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+0063 'c' */
    {.bitmap_index = 328, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0064 'd' */
    {.bitmap_index = 333, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+0065 'e' */
    {.bitmap_index = 337, .adv_w = 64, .box_w = 4, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0066 'f' */
    {.bitmap_index = 341, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2}, /* U+0067 'g' */
    {.bitmap_index = 346, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0068 'h' */
    {.bitmap_index = 351, .adv_w = 48, .box_w = 2, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0069 'i' */
    {.bitmap_index = 353, .adv_w = 48, .box_w = 2, .box_h = 10, .ofs_x = 0, .ofs_y = -2}, /* U+006A 'j' */
    {.bitmap_index = 356, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+006B 'k' */
    {.bitmap_index = 362, .adv_w = 48, .box_w = 2, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+006C 'l' */
    {.bitmap_index = 364, .adv_w = 144, .box_w = 8, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+006D 'm' */
    {.bitmap_index = 370, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+006E 'n' */
    {.bitmap_index = 374, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+006F 'o' */
    {.bitmap_index = 378, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2}, /* U+0070 'p' */
    {.bitmap_index = 383, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2}, /* U+0071 'q' */
    {.bitmap_index = 388, .adv_w = 64, .box_w = 4, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+0072 'r' */
    {.bitmap_index = 391, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+0073 's' */
    {.bitmap_index = 395, .adv_w = 64, .box_w = 3, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+0074 't' */
    {.bitmap_index = 398, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+0075 'u' */
    {.bitmap_index = 402, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+0076 'v' */
    {.bitmap_index = 406, .adv_w = 128, .box_w = 7, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+0077 'w' */
    {.bitmap_index = 412, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+0078 'x' */
    {.bitmap_index = 417, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2}, /* U+0079 'y' */
    {.bitmap_index = 422, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0}, /* U+007A 'z' */
    {.bitmap_index = 426, .adv_w = 80, .box_w = 4, .box_h = 10, .ofs_x = 0, .ofs_y = -2}, /* U+007B '{' */
    {.bitmap_index = 431, .adv_w = 48, .box_w = 1, .box_h = 10, .ofs_x = 1, .ofs_y = -2}, /* U+007C '|' */
    {.bitmap_index = 433, .adv_w = 80, .box_w = 4, .box_h = 10, .ofs_x = 0, .ofs_y = -2}, /* U+007D '}' */
    {.bitmap_index = 438, .adv_w = 96, .box_w = 6, .box_h = 2, .ofs_x = 0, .ofs_y = 2}, /* U+007E '~' */
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {.range_start = 32,
     .range_length = 95,
     .glyph_id_start = 1,
     .unicode_list = NULL,
     .glyph_id_ofs_list = NULL,
     .list_length = 0,
     .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
};

#if LVGL_VERSION_MAJOR == 8
/*Store all the custom data of the font*/
static lv_font_fmt_txt_glyph_cache_t cache;
#endif

#if LVGL_VERSION_MAJOR >= 8
static const lv_font_fmt_txt_dsc_t font_dsc = {
#else
static lv_font_fmt_txt_dsc_t font_dsc = {
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LVGL_VERSION_MAJOR == 8
    .cache = &cache
#endif
};

/*Initialize a public general font descriptor*/
#if LVGL_VERSION_MAJOR >= 8
const lv_font_t lv_font_helvetica_bold_12 = {
#else
lv_font_t lv_font_helvetica_bold_12 = {
#endif
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt, /*Function pointer to get glyph's data*/
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt, /*Function pointer to get glyph's bitmap*/
    .line_height = 12, /*The maximum line height required by the font*/
    .base_line = 2, /*Baseline measured from the bottom of the line*/
#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
    .subpx = LV_FONT_SUBPX_NONE,
#endif
#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8
    .underline_position = 0,
    .underline_thickness = 0,
#endif
    .dsc = &font_dsc, /*The custom font data. Will be accessed by `get_glyph_bitmap/dsc` */
#if LV_VERSION_CHECK(8, 2, 0) || LVGL_VERSION_MAJOR >= 9
    .fallback = NULL,
#endif
    .user_data = NULL};
#endif /* LV_FONT_HELVETICA_BOLD_12 */
